logger:
  file:
    path: /home/tetrixcorps/Desktop/glo/ota-testing/logs/smf.log
  level: info

global:
  max:
    ue: 1024
    peer: 64

smf:
  sbi:
    addr: 127.0.0.4
    port: 7777
  gtpc:
    addr: 127.0.0.4
  pfcp:
    addr: 127.0.0.4
  subnet:
    addr: 10.45.0.1/16
    dnn: internet

sbi:
  client:
    nrf:
      addr: 127.0.0.10
      port: 7777

upf:
  pfcp:
    addr: 127.0.0.7

parameter:
  no_ipv6: true
